all: README.md

README.md:
	echo '# this is for the unix workbench assignment' > README.md
	echo '* This is the date and time where makefile was ran: $(shell date +%Y-%m-%d:%H:%M:%S) *' >> README.md
	echo '* There are $(shell wc -l < guessinggame.sh) lines in the guessinggame.sh *' >> README.md